// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NC_Module.Data;

namespace NC_Module.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200914230630_ManyToMany")]
    partial class ManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NC_Module.Models.CorrAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("corrActions");
                });

            modelBuilder.Entity("NC_Module.Models.NonConf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("nonConfs");
                });

            modelBuilder.Entity("NC_Module.Models.NonConfCorrActions", b =>
                {
                    b.Property<int>("NonconfId")
                        .HasColumnType("int");

                    b.Property<int>("CorractionId")
                        .HasColumnType("int");

                    b.HasKey("NonconfId", "CorractionId");

                    b.HasIndex("CorractionId");

                    b.ToTable("nonConfCorrActions");
                });

            modelBuilder.Entity("NC_Module.Models.NonConfCorrActions", b =>
                {
                    b.HasOne("NC_Module.Models.CorrAction", "CorrAction")
                        .WithMany()
                        .HasForeignKey("CorractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NC_Module.Models.NonConf", "NonConf")
                        .WithMany()
                        .HasForeignKey("NonconfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
